//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseEvaluationEntities : DbContext
    {
        public CourseEvaluationEntities()
            : base("name=CourseEvaluationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentEvaluation> StudentEvaluations { get; set; }
        public virtual DbSet<StudentEvaluationAnswer> StudentEvaluationAnswers { get; set; }
        public virtual DbSet<vw_StudentAvailableEvaluation> vw_StudentAvailableEvaluation { get; set; }
        public virtual DbSet<vw_StudentIncompleteEvaluation> vw_StudentIncompleteEvaluation { get; set; }
    }
}
