//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEvaluation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentEvaluation()
        {
            this.StudentEvaluationAnswers = new HashSet<StudentEvaluationAnswer>();
        }
    
        public int StudentEvaluationID { get; set; }
        public int StudentID { get; set; }
        public int EvaluationID { get; set; }
        public System.DateTime CompletionDate { get; set; }
    
        public virtual Evaluation Evaluation { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEvaluationAnswer> StudentEvaluationAnswers { get; set; }
    }
}
