//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentIncompleteEvaluation
    {
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CourseNumber { get; set; }
        public int StudentID { get; set; }
        public int EvaluationID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
